### ISSUE TITLE
Android Things loader keeps loading

### ISSUE THREAD

**Issue by ghost** [thanksmister/androidthings-mqtt-alarm-panel#10]
Using the latest RPi3 image it happens that after loading the application, the Android Things loader (the black screen with three animated dots) comes back every few seconds. After 4-5 seconds I see again the application window, then again A.L. loader, in an endless loop.

When the application is visible I cannot do anything. 

I'm using a 3A bench power supply and I tried to burn two different SD cards, placed into two different RPi3. I connected an Ethernet cable to a DHCP-enabled router but even if I see some activity on the leds, it doesn't seem to have got an IP.

Is this a known behavior?

**Comment by thanksmister** [comment]
Could be the application is crashing.  Let me see if I can duplicate it on my RPi3 setup first, then track down the issue if its software related.

**Comment by thanksmister** [comment]
Definitely some issue but I think the application is stuck in some kind of OTA update loop.  I am investigating but I think Google created an issue when they updated Android Things console recently and introduced production and development flavors.  If I build and run the application on my RPi3 its working as expected but if I package that and install it to Android Things console, I get this constant looping issue.

**Comment by ghost** [comment]
Thanks for the update. Tell me if I can do anything useful.

**Comment by thanksmister** [comment]
Thanks, you have been helpful already by testing out the application.  I will get this sorted today and hopefully have a new version that works for you to test.

**Comment by thanksmister** [comment]
It appears that if I package an Android Things application for "production" it doesn't seem to work, but if I package it for "developer" it works as it should.  I think all previous versions were development, so using production seems to cause an endless update loop or causes it to break somehow.   I am just going to continue to use development which comes in handy because its easier to investigate issues.  Let me know if the latest version works for you, its v1.4.8.beta.4

**Comment by ghost** [comment]
Yeah, it works now! I'm going to play a bit :smile: Thanks!

**Comment by thanksmister** [comment]
I see that you hooked up or tried to use the motion sensor without one?  Got a crash report.   You need to have a PIR attached before using this feature, no way to check if its actually attached and crashes if it isn't and you use it...

**Comment by ghost** [comment]
No, I didn't try it. Anyway thanks for the hint: I will remember it!
