### ISSUE TITLE
Change screen orientation

### ISSUE THREAD

**Issue by ghost** [thanksmister/androidthings-mqtt-alarm-panel#11]
Feature request: is possible to add in the Display Settings a way to rotate the screen by 90° or 180°?

**Comment by thanksmister** [comment]
More has to happen before the screen can be rotated.   The UI must change to accomodate portrait layout instead of landscape.   This will take time to implement and test.

**Comment by ghost** [comment]
Ah ok, thank you for the explanation. Because your "twin" mobile app is responsive to screen rotation I thought it was just a matter of the lack of the accelerometer sensor. No problem.

**Comment by thanksmister** [comment]
It will happen I just need to port over the UI views so everything fits in portrait mode.
