### ISSUE TITLE
Sites using self signed certs don't show

### ISSUE THREAD

**Issue by thatkide** [thanksmister/androidthings-mqtt-alarm-panel#17]
My home assistant is using a self signed certificate, on both android things and android the page is blank.  I get the warning about the certificate, I click to accept then all I get is a blank background.  I have the root certificate installed on my phone yet I still get the certificate error even though the certificate shows valid if I use chrome.

**Comment by thanksmister** [comment]
At this time the browser doesn't allow insecure connections.  So it is probably throwing some kind of error on self-signed certificates.   In order to address this, the browser code within the application needs to be updated.

**Comment by thatkide** [comment]
Ahh ok thanks for the update.  I thought adding the root CA cert to the device would work but it didn't.  At least not for the alarm panel on an Android device, it did work for chrome  and other apps.  Thanks again.

**Comment by thanksmister** [comment]
I know that Android browser has issues with self signed certificates, especially from LetsEncrypt.  I’m not sure how to resolve the issue without getting a different certificate.

**Comment by thanksmister** [comment]
I will investigate how to allow self signed certificates for the Android browser but no guarantee in the time frame or success.

**Comment by thatkide** [comment]
I'm trying to compile mqtt alarm panel in Android studio but get this error 
"Error:Build Config field cannot have a null parameter".  
Have you run into this issue?  Sorry if this is a noob question, I'm just getting into android development.

**Comment by thanksmister** [comment]
The Android application uses default values from the local.properties files for testing.  The best way to deal with is to make them blank in the gradle file.  Under the productFlavors change the dev to this:

`dev {
            dimension "default"
            buildConfigField "String", BASE_ENVIRONMENT, '"DEV_ENVIRONMENT"'
            applicationId "com.thanksmister.iot.mqtt.alarmpanel"
            versionName "${versionMajor}.${versionMinor}.${versionPatch} Build ${versionBuild}-DEV"
            buildConfigField 'Integer', 'ALARM_CODE', '1234'
            buildConfigField 'String', 'DARK_SKY_KEY', '""'
            buildConfigField 'String', 'MAIL_GUN_KEY', '""'
            buildConfigField 'String', 'MAIL_GUN_URL','""'
            buildConfigField 'String', 'IMGUR_CLIENT_ID', '""'
            buildConfigField 'String', 'LATITUDE', '""'
            buildConfigField 'String', 'LONGITUDE', '""'
            buildConfigField 'String', 'MAIL_FROM', '""'
            buildConfigField 'String', 'MAIL_TO', '""'
            buildConfigField 'String', 'HASS_URL', '""'
            buildConfigField 'String', 'BROKER', '""'
            buildConfigField 'String', 'IMGUR_TAG', '""'
            buildConfigField 'String', 'TELEGRAM_TOKEN', '""'
            buildConfigField 'String', 'TELEGRAM_CHAT_ID', '""'
}`

Alternatively you can remove the BuildConfig.DEBUG information from the onCreate method of the MainActivity class:

`if(BuildConfig.DEBUG) {
            ....
}
`

**Comment by thatkide** [comment]
Thanks, I used your first suggestion and that took care of the issue.  Now I'm off to figure out these java deprecation warnings.
