### ISSUE TITLE
Image won't boot

### ISSUE THREAD

**Issue by theSC** [thanksmister/androidthings-mqtt-alarm-panel#18]
It just sits on the color wheel screen.
I am using a Raspberry Pi 3B (Not B+) with the official Raspberry Pi 7" screen and the latest image 1.5.0.2

**Comment by thanksmister** [comment]
Maybe check your power supply?   I have this issue with chargers that don't supply the correct power and the device won't fully boot.   Yeah, B+ isn't supported by Android Things (which sucks on their part).

**Comment by theSC** [comment]
I'm not getting the lightning bolt symbol at all and Rasbian will boot on the same set up just fine.
I will try a different power supply though just to see

**Comment by theSC** [comment]
Ah... my apologies upon closer inspection this Pi is a Pi 2B.
Sorry for wasting your time lol
