### ISSUE TITLE
Persistent MQTT messaged 

### ISSUE THREAD

**Issue by gravyflex** [thanksmister/androidthings-mqtt-alarm-panel#20]
Hello,
Thank you for this amazing app. 

There might be a way to make the MQTT messages persistent however I have been unable to find the settings in the app.

The issue is that when the alarm is armed from the app and home-assistant is restarted, the alarm is unarmed. I have already made the MQTT messages persistent so when the alarm is armed from within home-assistant I don't have this issue.

**Comment by thanksmister** [comment]
That’s entirely up to Home Assistant, the alarm state is set by Home Assistant.  So if you set the alarm to home fine the application, it’s actually Home Assistant se sing back the alarm home via MQTT to change the state of the application.  

So you need to find out how to restart Home Assistant and retain the alarm state.  I think this is discussed in the Home Assistant community forums.  

This is not an application issue or feature.
