### ISSUE TITLE
RPI 3B+ Won't Boot

### ISSUE THREAD

**Issue by wibyo** [thanksmister/androidthings-mqtt-alarm-panel#26]
Hi

its not my first time flash a sd card with etcher in case of using it on rpi ,

but it wont boot at all and with same sd and same devices i use, raspbian boot perfectly

is that because the release of iot_rpi3.img. v1.5.0-beta.2
NOT compatible with rpi 3b+ ???

at the boot i got power led solid and no act led blinking

do i have to connect network cable to it when boot ?

thank you

(black screen on boot)

**Comment by thanksmister** [comment]
The project only works on RPi3, it will not work on a RPi3B+ board because Google decided to end support for Raspberry Pi devices.   You will need to run this on an older Raspberry Pi 3 B, not the B+.
