### ISSUE TITLE
UI issues with Android 4.1 (Jelly Bean) devices

### ISSUE THREAD

**Issue by taugusti** [thanksmister/androidthings-mqtt-alarm-panel#4]
Hi,
I have problems with the app (downloaded from google play) because the config button is in the area where the tablet opens the navigation bar. So when ever I touch the screen the config button is hidden by the navigatio bar. It seems like the app is somehow defined as full screen so the navigation bar auto hides when the app is opened.
The tablet is a samsung galaxy tab 2 7.0"
Any suggestions for a fix or work around?

**Comment by thanksmister** [comment]
I would have to see images to understand the issue.  The app is designed to be a fullscreen dedicated alarm panel so it does open in fullscreen mode.  You can just swipe down to see the device controls, that's an Android thing not the app.

**Comment by taugusti** [comment]
Sure - I forgot to upload pictures..
I unedrstand that it is probably an android thing - I just hoped you had experienced it before and could help me get into configuration again... I managed to reinstall the app and and thereafter enter en config once...
![20180205_210615](https://user-images.githubusercontent.com/15052792/35826450-0c4a475a-0ab9-11e8-920b-def29cd338d7.jpg)
![20180205_210628](https://user-images.githubusercontent.com/15052792/35826452-0c672dde-0ab9-11e8-83e2-47338c34d245.jpg)

**Comment by taugusti** [comment]
the problem is that in full screen mode the navigation bar rolls over the app and makes the config-button unavailable...

**Comment by thanksmister** [comment]
But in one screenshot I see the configuration button, is that no clickable?

**Comment by taugusti** [comment]
no - I cannot click it - because when I touch the screen the navigation bar apears and covers the buttons...

**Comment by thanksmister** [comment]
Which version of Android are you using?  Seems to be an issue with the Android that you get the menu appearing on touch. I would have to do something specific for your version of Android to fix the issue or move the buttons entirely.

**Comment by taugusti** [comment]
Hi Again
It is a Samsung Galaxy Tab 2 7.0 and it runs android 4.1.2

**Comment by thanksmister** [comment]
Ok, I will take a look and see what I can do.  Its probably SDK related (4.1.2) so I will have to make an exception for that SDK version or lower to either not use fullscreen mode or allow the screen to resize if the system navigation appears.

**Comment by taugusti** [comment]
That would be fantastic - your help is much appreciated!

**Comment by thanksmister** [comment]
I think for JellyBean (Android 4.1) you need to leave the navigation in low profile mode instead of hidden.  This prevents it appearing on top of the UI and also doesn't causes the UI to resize on touch.   Here is my tests with the changes to fullscreen mode to JellyBean devices.  The navigation is always present, but in "low profile" which means the buttons are black until you touch the black bar. 

![screenshot_1517955454](https://user-images.githubusercontent.com/142340/35887256-7fd69192-0b72-11e8-9e45-ceeeffe3e060.png)

**Comment by thanksmister** [comment]
I have also discovered that you can't use the built-in Android webview for showing home automation pages, its out of date and can't render Home Assistant webpage.   That is just a limitation of Android  4.1.

**Comment by taugusti** [comment]
Hi again
I tried to find a way to enable low profile mode - but there are no settings for that :-( No settings about the navigation pane at all...
but I installed chrome on it from the play store - and that runs the home assistant site just fine...
/th

**Comment by thanksmister** [comment]
I am doing it with code, just testing a possible fix.   So when I do the next release the screen will look like the image I posted for JellyBean versions (Android SDK 4.1)

**Comment by taugusti** [comment]
ahh - fantastic - looking forward to see it! Do you want me to beta test for you?

**Comment by thanksmister** [comment]
Yeah that would be great, I will let you know when it's available.

**Comment by taugusti** [comment]
great!

**Comment by thanksmister** [comment]
You can opt-in to the beta program and download the beta version here: https://play.google.com/apps/testing/com.thanksmister.iot.mqtt.alarmpanel. 

The version is v.0.7.2

**Comment by taugusti** [comment]
It works!!! great!
Thanks! I really look forward to mount it on the wall this weekend!

**Comment by taugusti** [comment]
Should I close the issue?

**Comment by thanksmister** [comment]
I will close it, thanks for your help.
