### ISSUE TITLE
Ad-hoc camera snapshot via MQTT notification

### ISSUE THREAD

**Issue by warbringer** [thanksmister/androidthings-mqtt-alarm-panel#7]
Currently, the alarm panel wakes up when it detects messages on the MQTT broker for an alarm state change. This mechanism is also used to have the alarm panel speak a message via TTS by sending a message via the notification topic on the MQTT broker.

My suggestion is to use this same mechanism to trigger the camera to make a photo and have it sent via e-mail/telegram. This would provide ad-hoc capture capabilities to the alarm panel if needed so you can get a visual of who's in front of your alarm panel at all times and not just when it's successfully unlocked. The rationale for this is that a picture of someone **successfully** unlocking your alarm panel isn't that useful because they have the alarm code and are most likely allowed to be there anyway. What is more interesting is a picture of anyone who unsuccessfully tries to unlock the alarm or even anyone who passes by the alarm panel when nobody is supposed to be home. For this, you would want to have a PIR/motion/door sensor be able to send a notification to the MQTT broker via Home Assistant with a specific topic which the alarm panel will pick up. It will activate the camera, snap a picture and then send it via the configured options such as mailgun or telegram.

Additional features would be that the payload of the message to the MQTT broker tells the alarm panel if it should snap one or more pictures or maybe even capture a short video.

I could image a payload like this:
```
{"mode":"picture",
 "count":3,
 "interal":1
}
```
This would tell the panel to snap 3 pictures at a one-second interval.

```
{"mode":"video",
 "count":5,
}
```
This would tell the panel to capture a 5 second video.

The flow would look like this:
1. Z-Wave PIR sensor (or other connected technology) detects movement
2. Z-Wave PIR sensor reports state change to Home Assistant
3. Home assistant triggers automation that publishes a notification on the MQTT broker
4. Alarm panel is subscribed to the topic and picks up the notification, reads the payload.
5. Alarm panel engages the camera and snaps photo(s)/captures video
6. Photo(s)/video is sent to configured mailgun/telegram notifcation service

**Comment by thanksmister** [comment]
You've increased the scope already to include video capture.   I might break this into two requests because capturing images is currently supported.  Capturing video would require additional work.

**Comment by thanksmister** [comment]
> The rationale for this is that a picture of someone successfully unlocking your alarm panel isn't that useful because they have the alarm code and are most likely allowed to be there anyway.

The use case for having a photo captured is so that you know when a family member (like your partner or child) arrives home and turns off the alarm.  Call this a family alert feature.  Now we could make this take a photo on each "attempt" but I assume that the alarm is going to sound before anyone could possibly guess the code.  So catching bad actors who try to bypass the alarm upon breaking into your home isn't of a concern.

**Comment by thanksmister** [comment]
As of v1.4.8 this feature is now supported.  Closing.
