### ISSUE TITLE
v1.4.8-beta.3 release zip doesn't contain RPi image

### ISSUE THREAD

**Issue by ghost** [thanksmister/androidthings-mqtt-alarm-panel#9]
Hi! I'm trying to download your latest beta (v1.4.8-beta.3) but it has a size of 3,62 MB. It seems it has not the Android Things image inside. Would you mind to check it out?

**Comment by thanksmister** [comment]
Yep will do

**Comment by ghost** [comment]
Thanks! Any chance to get the latest version of Android Things? :grinning:

**Comment by thanksmister** [comment]
No because they've decided to remove the ability to dim screens in the latest version.

**Comment by thanksmister** [comment]
Ok, I have updated the file, should be fine now.  The next release will move to Android Things Preview 8, but this may break screen dimming, which would mean we'd get burned screens.
